// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iread_notifications_ms.DataAccess;

namespace iread_notifications_ms.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210927171210_UnRequireToken")]
    partial class UnRequireToken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("iread_notifications_ms.DataAccess.Data.Entity.Device", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Token");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("iread_notifications_ms.DataAccess.Data.Entity.DeviceNotification", b =>
                {
                    b.Property<string>("DeviceToken")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationsId")
                        .HasColumnType("int");

                    b.HasKey("DeviceToken", "NotificationId");

                    b.HasIndex("NotificationsId");

                    b.ToTable("DeviceNotifications");
                });

            modelBuilder.Entity("iread_notifications_ms.DataAccess.Data.Entity.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan>("SendAfter")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("iread_notifications_ms.DataAccess.Data.Entity.BroadcastNotification", b =>
                {
                    b.HasBaseType("iread_notifications_ms.DataAccess.Data.Entity.Notification");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.ToTable("TopicNotification");
                });

            modelBuilder.Entity("iread_notifications_ms.DataAccess.Data.Entity.SingleNotification", b =>
                {
                    b.HasBaseType("iread_notifications_ms.DataAccess.Data.Entity.Notification");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.ToTable("SingleNotifications");
                });

            modelBuilder.Entity("iread_notifications_ms.DataAccess.Data.Entity.DeviceNotification", b =>
                {
                    b.HasOne("iread_notifications_ms.DataAccess.Data.Entity.Device", "Devices")
                        .WithMany("DeviceNotifications")
                        .HasForeignKey("DeviceToken")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("iread_notifications_ms.DataAccess.Data.Entity.SingleNotification", "Notifications")
                        .WithMany("DeviceNotifications")
                        .HasForeignKey("NotificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devices");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("iread_notifications_ms.DataAccess.Data.Entity.BroadcastNotification", b =>
                {
                    b.HasOne("iread_notifications_ms.DataAccess.Data.Entity.Notification", null)
                        .WithOne()
                        .HasForeignKey("iread_notifications_ms.DataAccess.Data.Entity.BroadcastNotification", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("iread_notifications_ms.DataAccess.Data.Entity.SingleNotification", b =>
                {
                    b.HasOne("iread_notifications_ms.DataAccess.Data.Entity.Notification", null)
                        .WithOne()
                        .HasForeignKey("iread_notifications_ms.DataAccess.Data.Entity.SingleNotification", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("iread_notifications_ms.DataAccess.Data.Entity.Device", b =>
                {
                    b.Navigation("DeviceNotifications");
                });

            modelBuilder.Entity("iread_notifications_ms.DataAccess.Data.Entity.SingleNotification", b =>
                {
                    b.Navigation("DeviceNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
